# @package _global_
defaults:
  - project: integration_test_project
  - data: synth_data
  - preprocessing: default_preprocessing
  - training: default_training
  - evaluation: default_evaluation_synth
  - sweeper: optuna_singlethread
