# @package _global_
defaults:
  - project: test_project
  - data: test_data
  - preprocessing: default_preprocessing
  - training: default_training
  - evaluation: default_evaluation
  - _self_
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

model:
  model_name: xgboost # (str): Model, can currently take xgboost

hydra:
  sweeper:
    sampler:
      seed: 123
    n_trials: 4
    n_jobs: 4
    direction: maximize
    params:
      ++model.hyperparameters.n_estimators: choice(20, 30)
