# @package _global_
defaults:
  - project: test_project
  - data: test_data
  - preprocessing: default_preprocessing
  - model: xgboost
  - training: default_training
  - evaluation: default_evaluation
  - _self_
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    n_trials: 4
    n_jobs: 4
    direction: maximize
    params:
      model.xgboost.n_estimators: choice(40, 60)