defaults:
  - project: default_project
  - data: test_data
  - preprocessing: default_preprocessing
  - model: xgboost
  - training: default_training
  - evaluation: default_evaluation
  - _self_

project:
  name: psycop-t2d-testing