Combine medication, hba1c and diagnoses to find first date where the patient has t2d.

```{r}
source(here("src", "functions.r"))
```


## Include from BS only
```{r}
df_first_t2d_bs_only <- df_first_t2d_blood_sample %>% 
  rename(datotid_first_t2d_bs = datotid_start) %>% # Add BS
  left_join(df_first_date_of_t2d_medication_prescription) %>% 
  filter(datotid_first_t2d_bs < datotid_first_t2d_medication) %>% 
  left_join(df_first_t2d_diagnoses_combined) %>% 
  filter(datotid_first_t2d_bs < datotid_first_t2d_diagnosis) %>% 
  group_by(dw_ek_borger) %>% 
  filter(datotid_first_t2d_bs == min(datotid_first_t2d_bs)) %>% # Make sure to only have one record per patient
  select(dw_ek_borger, datotid_first_t2d_bs) %>% 
  distinct(dw_ek_borger, datotid_first_t2d_bs) %>% 
  left_join(df_first_psych_visit) %>% # 3010
  filter(datotid_first_psych_visit < datotid_first_t2d_bs) %>% # Keep only if diabetes is diagnosed after first psych visit: 810
  filter(!(event_start_date > datotid_first_t2d_bs)) %>% # Keep only after cohort start date: 606
  left_join(rename(df_first_t1d_diagnoses_combined, datotid_first_t1d_diagnosis = datotid_start), by = "dw_ek_borger") %>% 
  mutate(!(datotid_first_t1d_diagnosis < datotid_first_t2d_bs)) %>% 
  filter(is.na(datotid_first_t1d_diagnosis) | !(datotid_first_t1d_diagnosis < datotid_first_t2d_bs)) # Keep only if no t1d diagnosis before t2d: 601

dim(df_first_t2d_bs_only)
```

```{r}
write_csv(select(df_first_t2d_bs_only, dw_ek_borger), here("csv", "df_first_t2d_bs_only.csv"))
```