name: forced_admissions_inpatient
project_path: E:\shared_resources\clozapine\models\clozapine_no_text_outcome_model_medication_diagnoses_coercion
seed: 42

wandb:
  entity: psycop # Which entity to run wandb in.
  mode: offline # Which mode to run wandb in. Takes "run", "dryrun", "offline" and "disabled"
  group: clozapine # Which group to run wandb in.
  
  
gpu: true
