convert_to_boolean: False # (Boolean): Convert all prediction values (except gender) to boolean. Defaults to False
convert_datetimes_to: False # (str): Options include ordinal or False
imputation_method: "most_frequent" # (str): Options include 2most_frequent"
transform: null # (str|null): Transformation applied to all predictors after imputation. Options include "z-score-normalization"
feature_selection:
  name: null
  params:
    percentile: 10 # (int): Percent of features to keep. Defaults to 10.
