# @package _global_
preprocessing:
  convert_to_boolean: false
  convert_booleans_to_int: true
  drop_datetime_predictor_columns: true
  convert_datetimes_to_ordinal: false
  imputation_method: most_frequent
  scaling: z-score-normalisation
  feature_selection:
    name: chi2
    params:
      percentile: 20 # (int): Percent of features to keep. Defaults to 10.

hydra:
  sweeper:
    params:
      ++preprocessing.imputation_method: choice("most_frequent", "mean", "median", "null")
      ++preprocessing.scaling: choice("z-score-normalization", "null")
      ++preprocessing.feature_selection.name: choice("mutual_info_classif", "null")
      ++preprocessing.feature_selection.params.percentile: int(tag(log, interval(1, 90)))
