name: forced_admissions_inpatient
project_path: E:\shared_resources\forced_admissions_outpatient\models\full_model_without_text_features
seed: 42

wandb:
  entity: psycop # Which entity to run wandb in.
  mode: offline # Which mode to run wandb in. Takes "run", "dryrun", "offline" and "disabled"
  group: forced_admissions # Which group to run wandb in.
  
  
gpu: true
