```{r}
library("pacman")

p_load(tidyverse, here, future)
source(here("psycop_r_utils", "import_from_sql.r"))
plan(multisession)

```

```{r}
con <- DBI::dbConnect(
        odbc::odbc(),
        Driver = "SQL Server",
        Server = "BI-DPA-PROD",
        database = "USR_PS_Forsk",
        Trusted_Connection = "TRUE"
)
```


```{r}
df_administered_diabetes_medication <- con %>% 
  tbl(sql("SELECT * FROM [fct].FOR_Medicin_administreret_inkl_2021")) %>% 
  select(dw_ek_borger, datotid_ordination_start, atc) %>% 
  filter(substr(atc, 1, 3) == "A10") %>% 
  group_by(dw_ek_borger) %>% 
  filter(datotid_ordination_start == max(datotid_ordination_start)) %>% 
  filter(row_number() == 1) %>% 
  collect %>% 
  format_sql_import()
  
```

```{r}
df_inspect <- df_formatted_medication_administered %>% 
  head %>% 
  collect
```


```{r}
df_test_2 <- get_fct("FOR_LPR3kontakter_psyk_somatik_inkl_2021")
```


```{r}
df_formatted_medication_prescribed %<-% get_fct("FOR_Medicin_ordineret_inkl_2021")
```

```{r}
df_diabetes_medication <- df_formatted_medication_prescribed %>% 
  bind_rows(df_raw_medication_administered) %>% 
  filter(substr())
  
```

