```{r}
library("pacman")

p_load(tidyverse, here, future)
source(here("psycop_r_utils", "import_from_sql.r"))

```

```{r}
con <- DBI::dbConnect(
        odbc::odbc(),
        Driver = "SQL Server",
        Server = "BI-DPA-PROD",
        database = "USR_PS_Forsk",
        Trusted_Connection = "TRUE"
)
```

# Get first date of prescribed antidiabetic medication for each patient
## From only that administered
```{r}
df_first_administered_diabetes_medication <- con %>% 
  tbl(sql("SELECT * FROM [fct].FOR_Medicin_administreret_inkl_2021")) %>% 
  select(dw_ek_borger, datotid_ordination_start, atc) %>% 
  filter(substr(atc, 1, 3) == "A10") %>% 
  group_by(dw_ek_borger) %>% 
  filter(datotid_ordination_start == min(datotid_ordination_start)) %>% 
  collect %>% 
  format_sql_import() %>% 
  group_by(dw_ek_borger) %>% 
  filter(row_number() == 1) %>% 
  ungroup()
```

## From only that prescribed
```{r}
df_first_prescribed_diabetes_medication <- con %>% 
  tbl(sql("SELECT * FROM [fct].FOR_Medicin_ordineret_inkl_2021")) %>% 
  filter(substr(atc, 1, 3) == "A10") %>% 
  select(dw_ek_borger, datotid_ordinationstart, atc) %>% 
  rename(datotid_ordination_start = datotid_ordinationstart) %>% 
  group_by(dw_ek_borger) %>% 
  filter(datotid_ordination_start == min(datotid_ordination_start)) %>% 
  collect %>%   
  format_sql_import() %>% 
  group_by(dw_ek_borger) %>% 
  filter(row_number() == 1) %>% 
  ungroup()
```

## Combined
```{r}
df_first_date_of_diabetes_medication_prescription <- df_first_administered_diabetes_medication %>% 
  bind_rows(df_first_prescribed_diabetes_medication) %>% 
  group_by(dw_ek_borger) %>% 
  filter(datotid_ordination_start == max(datotid_ordination_start)) %>% 
  filter(row_number() == 1) %>% 
  rename(datotid_start=datotid_ordination_start)
```

