```{r}
library(pacman)
p_load(ggplot2, ggbeeswarm, tidyverse, here, ggbeeswarm)

source(here("psycop_r_utils", "import_from_sql.r"))
```


```{r}
df_demographics <- get_fct("FOR_kohorte_demografi_inkl_2021") %>% 
  format_sql_import() %>% 
  mutate(foedselsdato = ymd(foedselsdato))
```

```{r}
df_first_t2d_processed <- read_csv(here("csv", "df_first_t2d_bs_only.csv"))

df_first_psych_visit <- read_csv(here("csv", "df_first_psych_visit.csv"))
```

# Age at first t2d for patients with "true"" positives in cohort time
```{r}
df_age_at_first_t2d <- df_first_t2d_processed %>% 
  left_join(df_demographics) %>% 
  mutate(age_at_first_t2d = time_length(difftime(datotid_first_t2d, foedselsdato), "years"))
```

## Raincloud
```{r}
ggplot(df_age_at_first_t2d %>% mutate(group=1), aes(x = age_at_first_t2d, y = group)) +
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.3, 
    point_colour = NA) + 
  geom_boxplot(
    width = .1, 
    outlier.shape = NA
  ) +
  geom_quasirandom(
    size = 1,
    alpha = .3,
    position = position_jitter(
      seed = 1, width = .05
    ),
    groupOnX = FALSE
  ) + 
  coord_cartesian(xlim = c(1.2, NA), clip = "off") +
  scale_x_continuous(breaks = seq(5, 100, by = 5)) +
  ggtitle("Age at first t2d for patients with 'true' positives in cohort time")
```

## Cumulative distribution
```{r}
ggplot(df_age_at_first_t2d, aes(x = age_at_first_t2d)) +
  stat_ecdf(geom = "step") +
  scale_x_continuous(breaks = seq(5, 100, by = 5)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05)) +
   ggtitle("Age at first t2d for patients with 'true' positives in cohort time")
```

```{r}
df_without_children <- df_age_at_first_t2d %>% # 3284
  filter(age_at_first_t2d > 30) %>% # 2883
  filter(age_at_first_t2d < 90) # 2804
```

# Number of potentially true-positives that can generate predictions for increasing ∆t
```{r}
df_all_visits_combined <- read_csv(here("csv", "all_visits_combined.csv"))
```

```{r}
df_visits_for_size_of_prediction_window <- df_all_visits_combined %>% 
  rename(datotid_besoeg = datotid_start) %>% 
  inner_join(df_first_t2d_processed, by="dw_ek_borger") %>% 
  select(datotid_besoeg, datotid_first_t2d, dw_ek_borger) %>% 
  mutate(years_from_visit_to_t2d = time_length(difftime(datotid_first_t2d, datotid_besoeg), "years")) %>% 
  mutate(years_to_end_of_follow_up = time_length(difftime(max(datotid_besoeg), datotid_besoeg), "years")) %>% 
  filter(years_from_visit_to_t2d > 0) # Drop all visits that are before event %>% 
```

```{r}
df_size_of_prediction_window_with_selected_cols <- df_visits_for_size_of_prediction_window

for (i in 1:100) {
  colname = paste0("window_", i)
  
  df_size_of_prediction_window_with_selected_cols <- df_size_of_prediction_window_with_selected_cols %>% 
    mutate({{colname}} := if_else(((years_from_visit_to_t2d<i/12) & (years_to_end_of_follow_up>i/12)), 1, 0))
}
```

## For each visit
```{r}
df_size_of_prediction_window_summarised <- df_size_of_prediction_window_with_selected_cols %>% 
  summarise(across(starts_with("window"), mean, .names = "mean_{.col}")) %>% 
  pivot_longer(cols = starts_with("mean_"),
               names_to = "window_size_months",
               values_to = "percent_included") %>% 
  mutate(window_size_months = as.numeric(gsub("mean_window_", "", window_size_months)))
```

```{r}
filepath <- here("figures", "window_size_visits.png")

plot <- ggplot(df_size_of_prediction_window_summarised, aes(x = window_size_months, y = percent_included)) + 
  geom_point() +
  scale_x_continuous(breaks = seq(0, 100, by = 2))  +
  ggtitle("Proportion of potentially true-positive visits that are positive as a function of window size")

ggsave(filepath, plot, dpi = 300, width = 5, height = 3)
```

## For each patient
```{r}
df_predict_window_size_patients <- df_size_of_prediction_window_with_selected_cols %>% 
  group_by(dw_ek_borger) %>% 
  summarise(across(starts_with("window"), max, .names = "{.col}")) %>% 
  ungroup() %>% 
  summarise(across(starts_with("window"), mean, .names = "mean_{.col}")) %>% 
  pivot_longer(cols = starts_with("mean_"),
               names_to = "window_size_months",
               values_to = "percent_included") %>% 
  mutate(window_size_months = as.numeric(gsub("mean_window_", "", window_size_months)))
```

```{r}
filepath <- here("figures", "window_size_patients.png")

plot <- ggplot(df_predict_window_size_patients, aes(x = window_size_months, y = percent_included)) + 
  geom_point() +
  scale_x_continuous(breaks = seq(0, 100, by = 2)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05)) +
  ggtitle("Proportion of potentially true-positive patients that are positive as a function of window size")

ggsave(filepath, plot, dpi = 300, width = 5, height = 3)
```
