# Use Python 3.10 slim as the base image
FROM python:3.10
RUN apt-get update && apt-get install -y git-all

# Set the working directory to /app
WORKDIR /app

# Lazygit
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') && curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && tar xf lazygit.tar.gz lazygit && install lazygit /usr/local/bin && rm -rf lazygit lazygit.tar.gzRUN curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash

# Install dependencies
COPY dev-requirements.txt requirements.txt test-requirements.txt .
RUN pip install -r dev-requirements.txt

# Install the app
COPY . /app
RUN pip install -e .

# Initialise pre-commit
# Remove the .git repo afterwards, since the dev container bind-mounts the development repo
RUN git init . && pre-commit run
RUN inv static-type-checks