# Use Python 3.10 slim as the base image
FROM python:3.10
RUN apt-get update && apt-get install -y git

# Set the working directory to /app
WORKDIR /app

# Install dependencies
COPY pyproject.toml .
RUN pip install .[dev,tests]

# Install the app
COPY . /app/
RUN pip install -e .

# Developer experience
# Lazygit
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') && curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && tar xf lazygit.tar.gz lazygit && install lazygit /usr/local/bin && rm -rf lazygit lazygit.tar.gzRUN curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash