top_n_feature_importances: 10
positive_rates: [5, 3, 2, 1, 0.5, 0.3, 0.1]
save_model_predictions_on_overtaci: true
lookahead_bins: [2]
lookbehind_bins: [1, 3, 7, 10, 30, 180, 365, 730]
descriptive_stats_table: false
