name: scz_bp
project_path: E:\shared_resources\scz_bp\
seed: 42

wandb:
  entity: psycop # Which entity to run WanDB in.
  mode: offline # Which mode to run WanDB in. Takes "run", "dryrun", "offline" and "disabled"
  group: scz_bp # Which group to run WanDB in.
  
gpu: true
