name: cancer
seed: 42
project_path: E:\shared_resources\cancer\

wandb:
  entity: psycop # Which entity to run wandb in.
  mode: run # Which mode to run wandb in. Takes "run", "dryrun", "offline" and "disabled"
  group: cancer # Which group to run wandb in.

gpu: true
