from pathlib import Path
from typing import Protocol, runtime_checkable

import polars as pl
from confection import Config

from psycop.common.model_training_v2.trainer.task.base_metric import CalculatedMetric


@runtime_checkable
class BaselineLogger(Protocol):
    def info(self, message: str) -> None: ...

    def good(self, message: str) -> None: ...

    def warn(self, message: str) -> None: ...

    def fail(self, message: str) -> None: ...

    def log_metric(self, metric: CalculatedMetric) -> None: ...

    def log_config(self, config: Config) -> None: ...

    def log_artifact(self, local_path: Path) -> None: ...

    def log_dataset(self, dataframe: pl.DataFrame, filename: str) -> None: ...
