name: forced_admissions_inpatient
project_path: E:\shared_resources\forced_admissions_inpatient\full_model_with_sentence_transformer_and_tfidf_all_sfis_ngram_range_12_max_df_095_min_df_2_max_features_750_embeddings
seed: 42

wandb:
  entity: psycop # Which entity to run WanDB in.
  mode: offline # Which mode to run WanDB in. Takes "run", "dryrun", "offline" and "disabled"
  group: forced_admissions # Which group to run WanDB in.
  
  
gpu: true
