# @package _global_
model:
  name: naive-bayes # (str): Model name
  require_imputation: True # (bool): Whether the model requires imputation.
  args: # https://scikit-learn.org/stable/modules/naive_bayes.html#gaussian-naive-bayes
    var_smoothing: 0.000000001

# Parameters that will only take effect if running with --multirun
hydra:
  sweeper:
    params:
      # preprocessing
      ++preprocessing.post_split.scaling: choice(null, "z-score-normalization")
