# @package _global_
defaults:
  - project: default_project
  - data: default_data_frihae
  - preprocessing: default_preprocessing
  - model: xgboost
  - train: default_training
  - eval: default_evaluation
  - sweeper: optuna_multithread
