# @package _global_
model:
  name: ebm # (str): Model name, explainable boosting machine
  require_imputation: true # (bool): Whether the model requires imputation.
  args: # Documentiation: https://interpret.ml/docs/ebm.html#api
    max_bins: 256
    max_interaction_bins: 32
    binning: quantile
    mains: all
    interactions: 10
    outer_bags: 8
    inner_bags: 0
    learning_rate: 0.01
    validation_size: 0.15
    early_stopping_rounds: 50
    early_stopping_tolerance: 0.0001
    max_rounds: 5000
    min_samples_leaf: 2
    max_leaves: 3
    n_jobs: 1
    random_state: ${project.seed}

# Parameters that will only take effect if running with --multirun
hydra:
  sweeper:
    params:
      ++model.args.interactions: choice(0, 5, 10, 50)
      ++model.args.learning_rate: interval(0.001, 0.1)
      ++model.args.validation_size: interval(0.20, 0.05)
      ++model.args.min_samples_leaf: choice(1, 2)
      ++model.args.max_leaves: choice(2, 3, 4, 8, 16)
