name: psycop-t2d
seed: 42
wandb_mode: "offline" # Which mode to run WanDB in. Takes "run", "dryrun", "offline" and "disabled"
wandb_group: "psycop-t2d" # Which group to run WanDB in.
wandb_entity: "psycop" # Which entity to run WanDB in.
watcher:
  archive_all: false
  keep_alive_after_training_minutes: 5
  n_runs_before_eval: 1
gpu: false
