name: psycop-t2d-integration-testing
seed: 42
wandb_mode: "disabled" # Which mode to run WanDB in. Takes "run", "dryrun", "offline" and "disabled"
wandb_group: "integration_testing"
watcher: default_watcher
