name: psycop-t2d-integration-testing
seed: 42
wandb_mode: "disabled" # Which mode to run WanDB in. Takes "run", "dryrun", "offline" and "disabled"
wandb_group: "integration_testing"
wandb_entity: "psycop-t2d-testing" # Which entity to run WanDB in.
watcher:
  archive_all: true
  keep_alive_after_training_minutes: 5
  n_runs_before_eval: 1
gpu: false
