name: t2d
seed: 42

wandb:
  entity: psycop # Which entity to run WanDB in.
  mode: run # Which mode to run WanDB in. Takes "run", "dryrun", "offline" and "disabled"
  group: t2d # Which group to run WanDB in.
  
gpu: true
