def get_clinical_relevant_text_sfi_names() -> list[str]:
    """Returns a set of clinical relevant text sfi names. Notice that 'Konklusion' is replaced
    by 'Vurdering/konklusion' in 2020, so make sure to use both. 'Ordination'
    was replaced by 'Ordination, Psykiatry' in 2022, but 'Ordination,
    Psykiatri' is not included in the table. Use with caution.

    Returns:
        Set[str]: Set of valid text sfi names
    """
    return [
        "Observation af patient, Psykiatri",
        "Samtale med behandlingssigte",
        "Ordination",
        "Ordination, Psykiatri",
        "Aktuelt psykisk",
        "Aktuelt socialt, Psykiatri",
        "Aftaler, Psykiatri",
        "Medicin",
        "Aktuelt somatisk, Psykiatri",
        "Objektivt psykisk",
        "Kontaktårsag",
        "Telefonkonsultation",
        "Journalnotat",
        "Telefonnotat",
        "Objektivt, somatisk",
        "Plan",
        "Semistruktureret diagnostisk interview",
        "Vurdering/konklusion",
        "Konklusion",
        "Misbrugsoplysninger",
        "Alkohol og rusmidler",
        "Skadelig brug/afhængighed af rusmidler",
        "Psykiatrikonference",
    ]


def get_400_most_common_text_sfi_names() -> list[str]:
    """Returns a set of 400 most common text sfi names. Notice that 'Konklusion' is replaced
    by 'Vurdering/konklusion' in 2020, so make sure to use both. 'Ordination'
    was replaced by 'Ordination, Psykiatry' in 2022, but 'Ordination,
    Psykiatri' is not included in the table. Use with caution.

    Returns:
        list[str]: list of valid text sfi names
    """
    return [
        "Observation af patient, Psykiatri",
        "Aktuelt psykisk",
        "Medicin",
        "Objektivt psykisk",
        "Aftaler, Psykiatri",
        "Søvn og hvile, status",
        "Samtale med behandlingssigte",
        "Aktuelt socialt, Psykiatri",
        "Psykiatrikonference",
        "Screening for selvmordsrisiko",
        "Aktuelt somatisk, Psykiatri",
        "Telefonkonsultation",
        "Ernæring, status",
        "Journalnotat",
        "Plan",
        "KRAM (Kost, rygning, alkohol og motion)",
        "Kontaktårsag",
        "Aflysningsnotat",
        "Konklusion",
        "Hjemmebesøg",
        "Kontakt med anden myndighed",
        "Brøset Violence Checkliste (BVC)",
        "Samtale med pårørende",
        "Individuel psykoterapi",
        "Telefonnotat",
        "Søvn og hvile",
        "Udgang, Evaluering",
        "Visitationsnotat",
        "Behandling med øreakupunktur (NADA)",
        "Søvn og hvile, status (NY)",
        "Ordination",
        "Misbrugsoplysninger",
        "Samtykke til videregivelse af oplysninger, psykiatri",
        "Ratings og tests, Psykiatri",
        "Skærmning med samtykke",
        "Afslutningsnotat",
        "Psykoterapi i gruppe",
        "Miljøterapi",
        "Måling af patientvægt (kg)",
        "Udgang, ordination",
        "Fysioterapeutiske behandlingstiltag",
        "Patientidentifikation",
        "Vurdering af prøvesvar",
        "Tilstedeværende personale",
        "Deltagelse i aktiviteter",
        "Vurdering af bivirkninger",
        "Samtaler",
        "Somatisk undersøgelse",
        "Tidligere psykiatrisk",
        "Objektivt, somatisk",
        "Kontaktperson/kontaktkort",
        "Social anamnese, Psykiatri",
        "Signalement",
        "Medicingennemgang",
        "Dispositioner",
        "Psykoedukation i gruppe",
        "Blodtryksmåling",
        "Udlevering af journalmateriale, Psykiatri",
        "Information til patient om prøvesvar",
        "Diagnosenotat",
        "EKG",
        "Samtale med forældre",
        "Tidligere somatisk, Psykiatri",
        "ECT",
        "Motivation af patient forud for evt tvangsbehandling",
        "Skema 3 - Tvang - Bælte (Tvangsprotokol)",
        "Kost, rådgivning",
        "Semistruktureret diagnostisk interview",
        "Behandlingsplan, Psykiatri",
        "Motion/fysisk aktivitet, rådgivning",
        "Funktion og færdigheder, status",
        "Diætistnotat, Center for spiseforstyrrelse (CfS)",
        "Vurdering vedrørende sociale støttebehov",
        "Eftersamtale ved tvang",
        "Medicinordinationer fra FMK",
        "Informationsmateriale udleveret",
        "Vurdering af trusselsniveau/Risiko for vold",
        "Skolegang",
        "Udskillelser, status",
        "Netværksmøde",
        "Vejledning, instruktion, undervisning og rådgivning",
        "Visitering for effekter",
        "Vurdering af trusselsniveau",
        "Vurdering af prøver og undersøgelser",
        "Måling af puls",
        "Individuel psykoedukation",
        "Modtagelse af journalmateriale",
        "Samarbejde med patientrådgiver",
        "Forhåndstilkendegivelser, psykiatri",
        "Medicinafstemning udført ved start af patientkontakt",
        "Hud og slimhinder, status",
        "Nuværende psykisk",
        "Ernæring, status (NY)",
        "Vurdering/konklusion",
        "Aktindsigt/udleveret journalmateriale",
        "Tvang - frihedsberøvelse",
        "Måling af patienthøjde (cm)",
        "Psykoedukation i gruppe, manualiseret",
        "Set og vurderet af speciallæge i psykiatri",
        "E-mail konsultation",
        "Tvang - observation og pleje",
        "Gruppeaktivitet, Psykiatri",
        "Præmorbid psyke",
        "Medicinafstemning udført ved afslutning af patientkontakt",
        "Graviditet, fødsel og udvikling, Psykiatri",
        "Psykologisk undersøgelse",
        "Central temperaturmåling",
        "Psykosocial, status",
        "Ergoterapeutiske behandlingstiltag",
        "Skema 2 - Tvangsbehandling - Medicinering (Tvangsprotokol)",
        "Skærmning",
        "Rusmidler, rådgivning",
        "Vurdering af depressionssværhedsgrad med HAM-D17",
        "Somatisk udredning",
        "Inddragelse af samarbejdspartnere, Psykiatri",
        "Fysioterapeutiske undersøgelser, Psykiatri",
        "Handlingsplan, Psykiatri",
        "Sprog, kultur og religion, Psykiatri",
        "Smerter og sanseindtryk",
        "Alkoholrådgivning",
        "Resumé af behandlingsforløb",
        "Forespørgsel om børn i hjemmet",
        "Psykoedukation",
        "Kriminalitet",
        "Psykomotorisk bevægelsesterapi",
        "Skema 3 - Fiksering og magtanvendelse",
        "Drug test",
        "Øvrige organsystemer",
        "Primær ernæringsscreening",
        "Visitation af patienten for effekter",
        "Forældremyndighed",
        "Bestemmelse af Body Mass Index (BMI)",
        "Smerte og sanseindtryk, status",
        "Psykiatrisk dagbehandling",
        "Koordinationsplan, Psykiatri",
        "Skema 3 - Tvang - Remme (Tvangsprotokol)",
        "ECT-behandling",
        "Vederlagsfri medicin, bestilt til udlevering fra Hospitalsapoteket",
        "MAS-M maniscoringsskema (Modificeret Bech-Rafaelsen Maniskala)",
        "Udfærdigelse af erklæring",
        "Udgang, Psykiatri",
        "Henvisning",
        "Videokonsultation",
        "Kommunikation, status",
        "Inddragelse af forældre i behandlingen, Psykiatri",
        "Medicinoplysninger",
        "Psykologisk undersøgelsesrapport, Psykiatri",
        "Børn i hjemmet",
        "Udskrivningsaftale, Psykiatri",
        "Vurdering",
        "Plejeplan, individuel, Søvn og hvile",
        "MMSE Demens udredning",
        "Rådgivning vedrørende rygestop",
        "Patientinformation og - aftaler",
        "Medicinnotat. Hospitalsapoteket",
        "Koordinerende netværksmøde",
        "Blodsukkermåling, ikke fastende",
        "Samtykke til videregivelse af oplysninger",
        "Telefonisk receptudstedelse",
        "Objektivt",
        "Vurdering af funktionsniveau ved GAF",
        "Tidligere psykisk",
        "Kriminalitetsrecidiv, vurdering af risiko",
        "Farmakologisk risikoscreening",
        "Notat vedr. retslige forhold",
        "Pjecer udleveret",
        "Tilsyn",
        "Tvangsnotat",
        "Inddragelse af pårørende i behandling",
        "Ordination af ECT",
        "Sonde indgift",
        "Retslige foranstaltninger, Psykiatri",
        "Behandling med bilateralt elektroshock ECT",
        "Skema 1 - Frihedsberøvelse / tvangstilbageholdelse",
        "Udskillelse, Vandladning, status",
        "Træning af kropsbevidsthed",
        "Seksualitet, status",
        "Planlagt opfølgning",
        "Transkraniel magnetisk stimulationsbehandling",
        "Skema 2 - Tvangsbehandling",
        "Behandling med unilateralt elektroshock ECT",
        "Medicingivning ved intramuskulær injektion",
        "Allergi og intolerance",
        "Cirkulation, status",
        "Underretning til kommunen jfr. Serviceloven § 153",
        "Blodsukkermåling",
        "Koordination ved udskrivelse",
        "Udskillelse, Tarmfunktion, status",
        "NIP-indikator ikke opfyldt",
        "Resultat af kognitiv og neuropsykologisk testning",
        "Individuel psykoedukation, manualiseret",
        "Familieterapi",
        "Tilbud om psykoterapi",
        "Træning af kombinerede psykosociale færdigheder",
        "ECT, Anæstesinotat",
        "Skema 2 - Tvangsbehandling - ernæring (Tvangsprotokol)",
        "Livsstil",
        "Diætistnotat",
        "Kontaktkort",
        "Tværsektoriel samarbejdsaftale, Psykiatri",
        "Behandling med antipsykotikum",
        "Forebyggelse- og sundhedsfremmende plan",
        "Respiration, status",
        "Opfølgning hos egen læge, Ambulant",
        "Oplæring af patient i mestring af egen situation, Psykiatri",
        "Informeret samtykke",
        "Mestringsstøttende strategier",
        "Funktion og færdigheder, status (NY)",
        "Skadenotat",
        "Psykosocialt, status",
        "Supplerende oplysninger til ECT",
        "Institutionsbesøg",
        "Socialt",
        "Biomekanisk bevægelsesterapi",
        "Respiration og cirkulation, status",
        "Ugeplan",
        "Sonde, nasal/oral anlagt",
        "Hud og slimhinder, status (NY)",
        "Ernæringsproblem, obs og pleje af patient med",
        "Viden og udvikling. status",
        "Sekundær ernæringsscreening",
        "Måling af taljeomfang (cm)",
        "Viden og udvikling, status",
        "Træning af psykomotoriske funktioner",
        "Psykosocial, status (NY)",
        "Terapeutisk intervention",
        "Urinstix, værdier",
        "Inddragelse af børn i behandling",
        "Manuel terapi med henblik på kropsopfattelse",
        "Tidligere tvang",
        "Systematisk diagnostisk interview",
        "Blodsukkermåling, fastende",
        "ADHD-RS skema til forældre returneret udfyldt",
        "Tværfaglig konference",
        "ADHD-RS skema til skole/institution returneret udfyldt",
        "Akut ambulant, Psykiatri",
        "Udskillelse, Vandladning, status (NY)",
        "Ernæring givet per os",
        "Patient identifikation",
        "Kontakt til bistandsværge",
        "Ergo-/fysioterapeutisk undersøgelse eller vurdering",
        "TOKS, Psykiatri, totalscore (Tidlig opsporing af kritisk sygdom)",
        "Kost, rådgivnng",
        "Temperatur",
        "Saturation i %",
        "Særlige forhold",
        "KRAM",
        "Tolk",
        "Promille målt med alkoholmeter",
        "Ikke afsluttede og planlagte undersøgelser samt henvisninger",
        "Behandling af patientklagesager",
        "Aktuelt kognitivt",
        "Kommunikation, status (NY)",
        "Alkohol og rusmidler",
        "Udskillelse, Tarmfunktion, status (NY)",
        "Bevidsthed",
        "Kost",
        "Oplæring af patient i mestring af egen situation",
        "Pædagogisk beskrivelse, Psykiatri",
        "Present State Examination (PSE)",
        "Behandling med bilateral elektrokonvulsiv terapi (ECT)",
        "Forebyggelse af tvangsforanstaltninger",
        "Ernæringsplan",
        "COPM (Canadian Occupational Performance Measure)",
        "Mestringsplan",
        "Smerte og sanseindtryk, status (NY)",
        "Transkraniel magnetisk stimulationsbehandling (TMS)",
        "Udlevering af skriftligt informationsmateriale",
        "Supervision til institution",
        "Aktivitetstræning af fysisk funktion",
        "Aktivitet og deltagelse",
        "Absentering, kontakt under absentering",
        "Ergoterapeutiske undersøgelser. Psykiatri",
        "Neurologiske bivirkninger t med. antipsykotisk beh til stede",
        "Kognitiv test",
        "Opfølgning hos egen læge",
        "Kostafvigelser, Center for Spiseforstyrrelse (CfS)",
        "Medicin gennemgang",
        "TOKS, ordination",
        "TOKS (Tidlig opsporing af kritisk sygdom), totalscore",
        "Flerfamilieterapi",
        "Medicingivning ved injektion",
        "EKG taget",
        "Viden og udvikling, status (NY)",
        "Personlig hygiejne",
        "Bivirkninger (søvn/sedation) t. med. antipsyk. beh til stede",
        "Skema 2 - Tvangsbehandling - Legemlig lidelse (Tvangsprotokol)",
        "COVID-19, screening",
        "Ingen indikation for pårørendekontakt",
        "Diætetisk intervention",
        "Skema 3 - Tvang - Døraflåsning (Tvangsprotokol)",
        "Samtale med støtte- eller kontaktperson",
        "Vægt målt af andre",
        "Motion",
        "Underretning, Psykiatri",
        "Patientens vurdering af egen situation",
        "Sondeernæring givet",
        "Respirationsfrekvens pr min",
        "Sondefjernelse",
        "Samtale med patient om deltagelse i projekt",
        "Plejeplan, individuel, Ernæring",
        "Aktuelt",
        "Medicinafstemning udført ved udskrivelse",
        "Symptombehandling med akupunktur",
        "Samspil, relationer, behov - forældre/barn",
        "Træn. m.relation til kognitive og intellektuelle funktioner",
        "Aktindsigt",
        "Ernæringsvurdering, svært overvægtige",
        "Henvisning til ECT",
        "Tvang - bælte (fiksering og fysisk magtanvendelse)",
        "Kort resumé af indlæggelsesforløbet",
        "Seksualitet, status (NY)",
        "Ingen indikation for tilbud om psykoterapi",
        "Generelle pædagogiske interventioner",
        "Sikkerhedsplan",
        "Vurdering af sværhedsgraden af skizofrenisymptomer med PANSS-6",
        "MMSE (Mini Mental State Examination)",
        "Patientens netværk",
        "Kognitiv gruppeterapi",
        "MRSA screening",
        "Behandling med unilateral elektrokonvulsiv terapi (ECT)",
        "Urinundersøgelse med stix",
        "Skema 2 - Tvangsbehandling - ECT (Tvangsprotokol)",
        "Neuropsykologisk undersøgelse",
        "Konference",
        "Udarbejdelse af Udskrivningsaftale",
        "Plejeplan, individuel, Hud og slimhinder",
        "Ingen indikation for vurdering ved speciallæge i psykiatri",
        "Manuel terapi inkl. bløddelsbehandl.og ledmobilisering",
        "Udarbejdelse af Koordinationsplan",
        "Legeobservation",
        "Rygning (Tobak, snus, e-cigaretter)",
        "Telefonsamtale m.a. behandler/instans som led i beh.-forløb",
        "Cirkulation, status (NY)",
        "Træning og vedligeholdelse af psykisk funktion",
        "Indøvning af kommunikation og sociale færdigheder",
        "Medicinafstemning, ambulant",
        "Vejledning, instruktion, undervisning og rådgivning af pt.",
        "Absentering, risikovurdering og information til politi",
        "Resumé, Psykiatri",
        "Neuropsykologiske testresultater",
        "Tvangsbehandling - medicinering",
        "Seksuelle bivirkninger t. med. antipsykotisk beh. til stede",
        "Vurdering af prøvesvar og information til patient, Psykiatri",
        "Personale til stede",
        "Patienten modtaget i opvågningsafsnit",
        "Funktionsevnevurdering",
        "Kørselsforbud",
        "Afspændingsøvelser med fokus på respiration",
        "Kommunikation",
        "Transport til/fra hospital",
        "Visitationssamtale",
        "Befordringsskema sendt til kørselskontor",
        "Forslag til akut psykiatrisk medicinplan",
        "Respiration, status (NY)",
        "Tandstatus, anæstesi",
        "SAM screening, revurdering af evne til selvadministration",
        "Medicinafstemning under forløb",
        "Befordringsskema",
        "Socialrådgivernotat",
        "Absentering",
        "Skema 3 - Tvang - Beroligende medicin (Tvangsprotokol)",
        "Iltbehandling",
        "Receptudstedelse",
        "Personale tilstede",
        "Færdighedstræning i forbindelse med daglig livsførelse",
        "TOKS (Tidlig opsporing af kritisk sygdom), psykiatri, totalscore",
        "Psykolognotat",
        "Udsendelse af ADHD-RS skema til skole/institution",
        "Fravær af seksuelle bivirkninger t. med. antipsykotisk beh.",
        "Udsendelse af ADHD-RS skema til forældre",
        "Kontakt til hjemmesygeplejersken",
        "Seksualitetsproblemer, obs og vurdering af",
        "Resultat af personlighedspsykologisk testning",
        "Faldscreening",
        "Patienten modtaget på opvågningen",
        "Fravær af neurologiske bivirkninger t med. antipsykotisk beh",
        "Neurologisk undersøgelse",
        "Koordinationsplan",
        "Milepæle i barnets udvikling",
        "RKKP-indikator ikke opfyldt",
        "Udlevering af journalmateriale",
        "Smertescore NRS (Numeric Rating Scale 0-10)",
        "Kostvurdering - Klinisk diætist",
        "Seksualitet",
        "Væskeindtag pr.døgn",
        "Biokemi",
        "Ilt behandling",
        "Bivirkninger (vægtøgning) t med. antipsykotisk beh til stede",
        "Fravær af bivirkninger (søvn/sedation) t. med. antipsyk. beh",
        "Blodglukose taget",
        "Interview med institutionspersonale",
        "Skema 3 - Tvang - Fastholden (Tvangsprotokol)",
        "Telefonsamtale med andre myndigheder",
        "Angivelse af efterbehandlingstilbud",
        "Oplysningsskema, Psykiatri",
        "Søvnanamnese",
        "Ukendt",
        "Aftaler efter udskrivelsen",
    ]
