# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: tpe
  - override /hydra/launcher: joblib

hydra:
  sweeper:
    sampler:
      seed: 123
    n_trials: 1000
    n_jobs: 4
    direction: maximize