# @package _global_
preprocessing:
  pre_split:
    convert_to_boolean: false
    convert_booleans_to_int: true
    negative_values_to_nan: false
    drop_datetime_predictor_columns: true
    convert_datetimes_to_ordinal: false
    drop_patient_if_exclusion_before_date: false
    drop_visits_after_exclusion_timestamp: false
    min_prediction_time_date: 2015-01-01
    min_lookahead_days: 2
    lookbehind_combination: [1, 2, 3, 7, 10, 30, 180, 365, 730]
    min_age: 18
  post_split:
    imputation_method: "mean"
    scaling: "z-score-normalisation"
    feature_selection:
      name: "null"
      params:
        # percentile: 20 # (int): Percent of features to keep. Defaults to 10.

# Parameters that will only take effect if running with --multirun
hydra:
  sweeper:
    params:
      ++preprocessing.post_split.imputation_method: choice("most_frequent", "mean", "median", "null")
      ++preprocessing.post_split.scaling: choice("z-score-normalization", "null")
      ++preprocessing.post_split.feature_selection.name: choice("f_classif", "null")
      ++preprocessing.post_split.feature_selection.params.percentile: int(tag(log, interval(1, 90)))
      ++preprocessing.pre_split.lookbehind_combination: choice([1, 2, 3, 7, 10, 30, 180, 365, 730], [1, 7, 30], [1, 2, 7], [1, 7, 30, 180, 365, 730], [1, 7, 30, 365], [365], [180], [30], [7], [1])
      
