# @package _global_
defaults:
  - project: default_project
  - data: t2d_parquet
  - preprocessing: default_preprocessing
  - model: xgboost
  - train: default_training
  - eval: default_evaluation
  - sweeper: optuna_multithread
