# @package _global_
defaults:
  - project: integration_test_project
  - data: synth_data
  - preprocessing: default_preprocessing
  - train: default_training
  - model: xgboost
  - eval: evaluation_synth
  - sweeper: optuna_singlethread
