---
title: "T2D feasibility"
output: html_document
---

```{r}
library(DBI)

library(data.table)
library(dtplyr)
library(dplyr, warn.conflicts = FALSE)

library(lubridate)
library(ggplot2)
library(stringr)
library(tidyr)
library(tidyverse)

library(ggdist)
library(skimr)
library(patchwork)

source("E:/Users/adminmanber/Desktop/FeasibilityMapper/utils.r")
```

```{r}
conn <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "SQL Server",
  Server = "BI-DPA-PROD",
  database = "USR_PS_Forsk",
  Trusted_Connection = "TRUE"
)
```

##################
# Planned visits #
##################
```{r}
df_planned_visits_raw <- dbGetQuery(conn, "SELECT * FROM [fct].FOR_besoeg_fysiske_fremmoeder") %>% 
  clean_sql_import()

df_planned_psych_visits <- df_planned_visits_raw %>% 
  filter(substr(shakafskode_besoeg, 1, 4) == "6600") %>% 
  filter(psykambbesoeg == 1) %>% 
  select(dw_ek_borger, datotid_start)

```


```{r}
# Iterate over planned visits to only keep those, that are not within 3 months from last prediction
df_planned_with_3m_spacing <- df_planned_psych_visits %>% 
  drop_visits_within_break_window(months = 3, print_progress = TRUE)

```

#######
# Age #
#######
```{r}
df_demo_raw <- dbGetQuery(conn, "SELECT * FROM [fct].FOR_kohorte_demografi") %>% 
  clean_sql_import()

df_demo <- df_demo_raw %>% 
  select(foedselsdato, dw_ek_borger)

```


###############
# First psych #
###############
```{r}
df_psyk_raw <- dbGetQuery(conn, "SELECT * FROM [fct].FOR_besoeg_fysiske_fremmoeder") %>% 
  clean_sql_import()

df_first_p <- df_psyk_raw %>% 
  select(dw_ek_borger, datotid_start) %>% 
  group_and_keep_record_with_min_value_on_col(dw_ek_borger, datotid_start) %>% 
  rename(datotid_f_psych = datotid_start)

```


###############
# T2D samples #
###############
# Raw
```{r}
df_hba1c_raw <- dbGetQuery(conn, "SELECT * FROM [fct].FOR_LABKA_NPU27300_HbA1c") %>% 
  rename_with(tolower)
```

```{r}
df_maybe_t2d <- df_hba1c_raw %>% 
  select(datotid_godkendtsvar, svar, dw_ek_borger) %>% 
  mutate(svar = as.numeric(svar)) %>% 
  filter(svar > 47) %>% 
  select(-svar) %>% #Remove incidences that are before first psych contact
  left_join(df_first_p) %>% 
  filter(datotid_f_psych < datotid_godkendtsvar) %>% 
  group_by(dw_ek_borger) %>% 
  arrange(datotid_godkendtsvar, .by_group = TRUE) %>% # Keep only first row
  filter(row_number() == 1) %>% 
  rename(datotid_maybe_t2d = datotid_godkendtsvar) %>%
  mutate(datotid_maybe_t2d = ymd_hms(datotid_maybe_t2d)) 


df_probably_t2d <- df_hba1c_raw %>% 
  select(datotid_godkendtsvar, svar, dw_ek_borger) %>% 
  mutate(svar = as.numeric(svar)) %>% 
  filter(is.na(svar) == FALSE) %>%  
  left_join(df_first_p) %>% #Remove incidences that are before first psych contact
  filter(datotid_f_psych < datotid_godkendtsvar) %>% 
  group_by(dw_ek_borger) %>% # Check if first HbA1c was normal
  arrange(datotid_godkendtsvar, .by_group=TRUE) %>% 
  mutate(first_hba1c_normal = svar[1] < 48) %>% 
  filter(svar > 47 & first_hba1c_normal == TRUE) %>% 
  group_by(dw_ek_borger) %>% 
  arrange(datotid_godkendtsvar, .by_group = TRUE) %>% 
  filter(row_number() == 1) %>% # Keep only first match
  select(datotid_godkendtsvar) %>% 
  rename(datotid_probably_t2d = datotid_godkendtsvar) %>% 
  mutate(datotid_probably_t2d = ymd_hms(datotid_probably_t2d))

```


########
# Plot #
######## 
##############
# Age at T2D #
##############
```{r}
gen_plot_age_df <- function(df, outcome) {
  df_out <- df %>% 
    left_join(df_demo) %>% 
    mutate(age_at_t2d = interval(foedselsdato, {{outcome}}) / years(1))
  
  return(df_out)
}

df_plot_probably_t2d <- gen_plot_age_df(df_probably_t2d, datotid_probably_t2d)

df_plot_maybe_t2d <- gen_plot_age_df(df_maybe_t2d, datotid_maybe_t2d)
```

```{r}
save_histogram <- function(df, x_var, filename) {
  gg <- ggplot(df, aes(x={{x_var}}, y = ifelse(..count.. > 4, ..count.., 0))) +
    geom_histogram(binwidth=1) +
    labs(
      title = filename,
      x = "Age at incident T2D (years)",
      y = "Count"
    ) +
    scale_x_continuous(
      breaks = seq(15, 100, by=5),
      limits = c(15, 100)
    )
  
  ggsave(str_c("figures/", filename, ".png"), width = 20, height = 10, dpi = 100, units = "in")
  
  gg
}

save_histogram(df_plot_probably_t2d, age_at_t2d, "age_at_first_t2d_hba1c_after_normal_hba1c")
save_histogram(df_plot_maybe_t2d, age_at_t2d, "age_at_first_t2d_hba1c")

```


##################################
# Time from planned visit to T2D #
##################################
```{r}
gen_planned_to_event_df <- function(df_event, event_col, df_planned_visits) {
  df_out <- df_event %>% 
    inner_join(df_planned_with_3m_spacing) %>%
    rename(visit_start = datotid_start) %>% 
    mutate(years_since_visit = interval(visit_start, {{event_col}}) / years(1))
  
}

df_planned_to_probable_t2d <- gen_planned_to_event_df(df_event=df_probably_t2d, 
                                                      event_col=datotid_probably_t2d, 
                                                      df_planned_visits=df_planned_psych_visits)

df_planned_to_maybe_t2d <- gen_planned_to_event_df(df_event=df_maybe_t2d, 
                                                   event_col=datotid_maybe_t2d, 
                                                   df_planned_visits=df_planned_psych_visits)

```


```{r}
save_combined_histogram_boxplot <- function(df, x_var, filename) {
  gg <- ggplot(df, aes(x={{x_var}})) +
    scale_x_continuous(
      breaks = seq(0, 10, by=0.25),
      limits = c(0, 10)
    )
  
  hist <- gg +
    geom_histogram(
      aes(y = ifelse(..count.. > 4, ..count.., 0)),
      binwidth = 0.25
    ) 
  
  box <- gg +
    geom_boxplot(outlier.shape = NA)
  
  combined <- hist + box + plot_layout(nrow = 2, height = c(2, 1))
  
  ggsave(str_c("figures/", filename, "_histogram.png"), width = 20, height = 20, dpi = 100, units = "in")
  
  combined
}

save_combined_histogram_boxplot(df_planned_to_maybe_t2d, years_since_visit, "years_until_maybe_t2d_for_visit_histogram")
save_combined_histogram_boxplot(df_planned_to_probable_t2d, years_since_visit, "years_until_probable_t2d_for_visit_histogram")

```

# How much time is there from planned visit to end of follow-up?
```{r}
df_planned_to_end_of_followup <- df_planned_with_3m_spacing %>% 
  mutate(years_till_end_of_followup = (as.period(ymd_hms("2020-10-28 00:00:00") - datotid_start)) / years(1))

save_combined_histogram_boxplot(df_planned_to_end_of_followup, years_till_end_of_followup, "years_from_visit_to_end_of_followup")
```

