name: Check for .rej files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-for-rej-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for .rej files
        run: |
          if [[ find . -type f -name "*.rej" ]]; then
            echo "Error: Found .rej files in the repository."
            exit 1
          else
            echo "No .rej files found in the repository."
          fi
