# .rej files occur when cruft update could not merge two files.
# They need to be handled, but are easy to miss if there's no CI 
name: Check for .rej files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-for-rej-files:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          pip install invoke tox

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for .rej files
        run: |
          inv test-for-rej
