name: Cruft Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cruft-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Cruft
        run: pip install cruft

      - name: Run Cruft Check
        id: cruft_check
        run: |
          if cruft check; then
            echo "Cruft check passed"
            echo "cruft_failed=0" >> $GITHUB_OUTPUT
          else
            echo "Cruft check failed"
            echo "cruft_failed=1" >> $GITHUB_OUTPUT
            exit 0
          fi

      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.cruft_check.outputs.cruft_failed  == 1}}
        id: add_comment
        with:
          message: |
            ✨ There is a newer version of contious integration files or other tooling available ✨

            Feel free to either:
            🥳 Keep up the good work or
            🧠 If you're feeling extra helpful, run `cruft update` and merge in the updates

      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.cruft_check.outputs.cruft_failed  == 0 && steps.add_comment.outputs.comment-updated == true}}
        with:
          message: |
            🌟 Cruft has been updated, thanks a lot! 🌟
