name: docker-publish
on:
  push:
    tags:
      - "v*"
  pull_request: # TODO: Disable this when we have tested the CI/CD
    branches:
      - "main"
  workflow_dispatch:
    # TODO: Skip if no requirements or dockerfile changes

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: docker-publish
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/aarhus-psychiatry-research/psycop-common-kubeflow
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          # Push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64
          file: Kubeflow
          tags: ${{ steps.meta.outputs.tags }}
