# GitHub action to check if pre-commit has been run. Runs from .pre-commit-config.yaml, where the pre-commit actions are.

name: modified-library-files

on:
  pull_request:
    paths:
        - "psycop/common/**"
jobs:
  modified-library-files:
    permissions:
      pull-requests: write
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        id: add_comment_safety
        with:
          message: |
            Looks like your PR modifies shared library files in `psycop/common/`. 
            
            We highly recommend getting your code reviewed by one of the core maintainers to avoid breaking other projects that depend on these files :-)