# This workflow will install Python dependencies, run pytests and run notebooks
# then it will in python 3.9 (ubuntu-latest) create a badge with the coverage
# and add it to the PR. This badge will be updated if the PR is updated.

name: publish-devcontainer
on:
  push:
    branches: main

jobs:
  pytest:
    strategy:
      matrix:
        docker_platform: [linux/amd64, linux/arm64]
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set up QEMU for multi-architecture builds
        if: matrix.docker_platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx for multi-architecture builds
        if: matrix.docker_platform == 'linux/arm64'
        uses: docker/setup-buildx-action@v2
        with:
          use: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create github hosts file
        run: | # If this file is not created, the dev container fails because of non-existant mount
          mkdir -p ~/.config/gh
          touch ~/.config/gh/hosts.yml

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aarhus-psychiatry-research/psycop-common
          platform: ${{ matrix.docker_platform}}
          push: always