name: CI Pytest
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.9]
        
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Checkout repo
      uses: actions/checkout@v3

    ## setup chromedriver for saving Altair plots
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.7

    ### Caching
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2.1.6
      with:
        path: |
          .venv
          poetry.lock
        # Cache the complete venv dir for a given os, python version, pyproject.toml
        key: venv-${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.github/workflows/cache_version') }}

    ### Installing
    - name: Install Project
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install -vvv
    
    ### Run tests
    - name: Run pytest
      run: |
        poetry run pytest --cov=src --cov-report term-missing --color=yes
