

name: CI Pytest
on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    ### Caching
    - name: Load cached $HOME/.local
      uses: actions/cache@v2.1.6
      with:
        path: ~/.local
        key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/pytest.yml') }}
    - name: Cache Poetry cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: 'poetry'
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        poetry install
    - name: Run and write pytest
      run: |
        set -o pipefail
        poetry run pytest --cov=src --cov-report term-missing | tee pytest-coverage.txt
