name: Semantic Release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    # Checkout action is required for token to persist
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.MB_PERSONAL_ACCESS_TOKEN }}

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.32.0
      with:
        github_token: ${{ secrets.MB_PERSONAL_ACCESS_TOKEN}}
        # Remember to copy the tool.semantic_release section from pyproject.toml 
        # as well
        # To enable pypi, 
        # 1) Set upload_to_pypi to true in pyproject.toml and
        # 2) Set the pypi_token in the repo
        # 3) Uncomment the two lines below
        # repository_username: __token__
        # repository_password: ${{ secrets.PYPI_TOKEN }}