# GitHub action to check if pre-commit has been run. Runs from .pre-commit-config.yaml, where the pre-commit actions are.

name: review-safety-checklist

on:
  pull_request:
jobs:
  review-safety-checklist:
    permissions:
      pull-requests: write
    if: ${{ github.event.review.state == 'pending' }}
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v2
        id: add_comment_safety
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Remember to prioritise safety in your review. Make sure the following points have been covered:
              - [ ] New packages have been vetted
              - [ ] Only aggregate data is saved to disk
              - [ ] Comments or examples do not contain actual data
              - [ ] The code does not log sensitive information TEST