name: "Close stale issues and PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          days-before-issue-stale: 14
          days-before-issue-close: 7
          stale-issue-message: "This issue is stale because it has been open 14 days with no activity. Feel free to remove stale label or comment or this will be closed in 14 days."
          close-issue-message: "This issue was closed because it has been stale for 14 days with no activity."
          days-before-pr-stale: 14
          days-before-pr-close: 7
          stale-pr-message: "This PR is stale because it has been open 14 days with no activity. Feel free to remove stale label or comment or this will be closed in 7 days."
          close-pr-message: "This PR was closed because it has been stale for 7 days with no activity. Feel free to re-open it if you still want to work on it."
