name: CI Pytest
on:
  pull_request:
    branches: [ main, dev ]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.9]
        poetry-version: [1.1.15]
        cache-version: [0.0.0] # Change this number if you want to manually invalidate all caches
        
    steps:
    ### Setup prerequisites
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: $ {{ matrix.python-version }}

    - name: Checkout repo
      uses: actions/checkout@v3

    ### Caching
    - name: Cache poetry and venv
      id: cache-poetry-and-venv
      uses: MartinBernstorff/cache-poetry-and-venv@latest
      with:
        poetry-version: ${{ matrix.poetry-version }}
        cache-version: ${{ matrix.cache-version }}

    # Installing
    - name: Install Poetry
      if: steps.cache-poetry-and-venv.outputs.poetry-cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: ${{ matrix.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install Project
      if: steps.cache-poetry-and-venv.outputs.venv-cache-hit != 'true'
      run: poetry install -vvv
    
    ### Run tests
    - name: Run pytest
      run: |
        poetry run pytest --cov=src --cov-report term-missing --color=yes
