# GitHub action to run Snyk check for vulnerabilities in all requirement files.

name: vulnerability_scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Get git branches
        run: |
          git fetch origin main
          git branch

      - name: Install dependencies
        shell: bash
        run: |
          pip install invoke
          inv install-requirements

      - name: Install snyk
        run: npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          inv vulnerability-scan --modified-files-only
