# GitHub action to run Snyk check for vulnerabilities in all requirement files.

name: vulnerability_scan

on:
  pull_request:
  push:
    branches: [main]

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create github hosts file
        run: | # If this file is not created, the dev container fails because of non-existent mount
          mkdir -p ~/.config/gh
          touch ~/.config/gh/hosts.yml

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/aarhus-psychiatry-research/psycop-common
          push: filter
          runCmd: |
            git fetch origin main && git branch && inv vulnerability-scan --modified-files-only
          env: |
            SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}